#
# Project config
#

# Set timezone
timezone: Europe/London

# Compile SASS
sass:
  sass_dir: _sass
  style: compressed

# Set base URL
url: 'https://chrisporter.uk'

# Site meta fallbacks
name: Chris Porter, graphic designer
metaDescription: The online presence of graphic designer, Chris Porter
metaSocialImage: /assets/filename.jpg
